### ISSUE TITLE
Wifi password cannot contain spaces?

### ISSUE THREAD

**Issue by jeroenh** [SIDN/sidn_openwrt_pkgs#1]
I've just tried to configure a GL-Inet AR150 with the Valibox firmware. It boots and when I try to connect, I get the welcome page to setup a wifi password and admin password.

I've tried two different wifi passwords, both containing one or more spaces. After rebooting, it was not possible to join the wireless network from my OSX machine. It insisted that the password was incorrect.

**Comment by tjeb** [comment]
urlencoded data handling error. Should be fixed in commit 6fdbcf03e3bb5ae9becd6738a91ddc9563633a07
