### ISSUE TITLE
[Feature request] Update unbound to the latest version (for now 1.13.0)

### ISSUE THREAD

**Issue by BKPepe** [SIDN/sidn_openwrt_pkgs#13]
Hi guys,

I noticed that in your repository, there is a version of Unbound 1.6.0 because we are building your packages for Turris routers.
Will it be possible to update it to the latest version, please? The current latest version of Unbound is 1.13.0

**Comment by tjeb** [comment]
Right, that had been way too long. Updated in the master and development branches.

**Comment by BKPepe** [comment]
Thank you! Just for sake of completeness, it was done in this commit https://github.com/SIDN/sidn_openwrt_pkgs/commit/5a0a6edd625b8666243621c6087c515f86e0f24f
