### ISSUE TITLE
Autonta does not exclude double-update 

### ISSUE THREAD

**Issue by ElmerLastdrager** [SIDN/sidn_openwrt_pkgs#2]
If you update, the window confirming that you submitted the update to occur is shown. It tells you that you **can** close the window.
If you are the kind of person that does not close the window, and you refresh the window after the valibox has updated and restarted, you make the valibox update and restart again.

Preferably, the confirmation webpage should not reinstall the valibox if it is refreshed.

**Comment by tjeb** [comment]
Should be fixed in 32a1e579c9dee1384d4526bcc567223ef3c90aa7, will be added to next release
